
# ChangeLog file
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml

# Driver class
driver=org.postgresql.Driver

# URL to the database
url=jdbc:postgresql://localhost:5432/geobytesdb
#referenceUrl=hibernate:spring:com.byteworks.dev.backendservices.entities?dialect=org.hibernate.dialect.PostgreSQLDialect

# Database credentials
username=postgres
password=papi

#spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
